version: '3'
services:
  workaround-mysql:
    container_name: ms/irock
    image: mysql
    environment:
      MYSQL_DATABASE: coffeehousems
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3308:3306"
    restart: always
  workaround:
    depends_on: 
      - workaround-mysql
    restart: always
    # will build ./docker/workaround/Dockerfile
    build: ./
    working_dir: /
    expose:
      - "8080"
    command: "mvn clean spring-boot:run"